### ISSUE TITLE
Blank screen issue still persist on iPad

### ISSUE THREAD

**Issue by LaxusiC** [PoomSmart/YouTube-X#10] opened 2024-06-27 08:56 UTC
![616CEEB2-60DA-4481-965D-D410B042AC49](https://github.com/PoomSmart/YouTube-X/assets/9650215/6e923e46-dedd-49cf-83be-37b8f9091dc6)

Youtube version: 19.25.4
Tweak versiom: 1.6.9
Jailbreak: Dopamine 2.0 iPadOS 16.0

**Comment by JackPlaysGames0510** [comment] 2024-06-27 09:31
I get the same on my iPhone

**Comment by peimingtai** [comment] 2024-06-28 04:57
Ads still appear, pls fix it

**Comment by oldman20** [comment] 2024-06-29 03:52
How to install this app? inject deb into ipa?

**Comment by indrapalijama** [comment] 2024-06-29 18:29
> ![616CEEB2-60DA-4481-965D-D410B042AC49](https://github.com/PoomSmart/YouTube-X/assets/9650215/6e923e46-dedd-49cf-83be-37b8f9091dc6)
> 
> 
> 
> Youtube version: 19.25.4
> 
> Tweak versiom: 1.6.9
> 
> Jailbreak: Dopamine 2.0 iPadOS 16.0

try downgrade to 1.6.6, somehow it fixed the issue for me

**Comment by oldman20** [comment] 2024-07-01 04:39
> How to install this app? inject deb into ipa?

anyone pls teach me?

**Comment by indrapalijama** [comment] 2024-07-01 15:52
> Does the issue still exist in v1.6.10 ?

hey poom, the issue is fixed in this new update, you can close this issue
Thanks!

**Closed** 2024-07-01 15:56 UTC
